name: MBedwarsSpectatorSettingsAddon
version: 1.0.2
depend: [MBedwars]
authors: [dejwideek]
main: pl.dejwideek.mbwspectatorsettingsaddon.SpectSettingsAddon
commands:
  spectsettingsreload:
    aliases:
      - ssareload
      - ssreload
      - spectatorsettingsreload
    description: Reload config files